# Generated by Django 2.0.6 on 2018-07-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photoshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('photo', models.ImageField(upload_to='', verbose_name='photos/noimage.jpg')),
                ('created_date', models.CharField(max_length=8)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
